(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by CoffeeScript 1.10.0
var m;

m = angular.module('nl2br', []);

(function() {
  var Filter;
  Filter = function($sce, $sanitize) {
    return function(input) {
      var output;
      output = input || '';
      output = output.replace(/</g, '&lt;');
      output = output.replace(/>/g, '&gt;');
      output = $sanitize(output);
      output = output.replace(/(&#10;&#13;|&#13;&#10;|&#10;|&#13;)/g, '<br>');
      return $sce.trustAsHtml(output);
    };
  };
  Filter.$inject = ['$sce', '$sanitize'];
  return m.filter('nl2br', Filter);
})();

},{}]},{},[1])