// Generated by CoffeeScript 1.10.0
var m;

m = angular.module('nl2br', []);

(function() {
  var Filter;
  Filter = function($sce, $sanitize) {
    return function(input) {
      var output;
      output = input || '';
      output = output.replace(/</g, '&lt;');
      output = output.replace(/>/g, '&gt;');
      output = $sanitize(output);
      output = output.replace(/(&#10;&#13;|&#13;&#10;|&#10;|&#13;)/g, '<br>');
      return $sce.trustAsHtml(output);
    };
  };
  Filter.$inject = ['$sce', '$sanitize'];
  return m.filter('nl2br', Filter);
})();
